branches:
  only:
  - master
deploy:
  provider: s3
  access_key_id: AKIAIADP5KLP7FW3PBXA
  secret_access_key:
    secure: o3h+NwGPdcWN+X/iQKTyBBvE55meKF9UzaaY24w1vJjJ74SkigqrPQlHwArOquIw62V4FpkcqLYKQ0S+RVvXnldn3iFOXi1c0FL81LcB7QXTmcPiE9AZ2lO6qVynvOEntQkaGnTSC12KhmsY4DfMzFMKqKlGEvfsgq6MzfN9HAEtDgrvcjSCyYtEFea1WIF3z8HZBO87nz7A38ATCyY1QINRYpOMD7vp3FEKspxuE6fKnJrGbAPueOlVbQydliyLDfIbI8A+FPRmBtZ7oZIfKvL3I9ott0wq+e9SgLt4FGNBlawjMe/84fmQcMEkhmmS58hd7CaT84as4XCT3RyASDBf/sKV133AHgbsijfn3/gx2R8lqxCByrc2G+rfS7AUtHCTXAjTSXC1sJJJmxHMAqIOhTan31+0j8rUkddZarikvHlOgpJYJrlS1hO9jWhBjVw9TF5ioE8mrKTM5hAvDouCMBuS4HeCDzJoRfVvjw7hepVI/jM/lZJL76RPYrLBeMnV0ZKIw+AU7H4pcFSDfCGgNf4JD5efZfq1k1VyFO9b3lypcVJpqeuMuBEkKOEussvq9rUgWNoNOG7rUoOYbCVpuMWvKXj+bUrY4E1Jzezr2CuvP7wp7WSDr4g4VilzQjnkJbr9V3VWBbIsBm+E4uGWaQ4M8gWxQSLZr0DL3fY=
  bucket: theme.instedd.org
  skip_cleanup: true
  on:
    branch: master
