branches:
  only:
  - master
deploy:
  matrix:
  - provider: s3
    access_key_id: AKIAIADP5KLP7FW3PBXA
    secret_access_key:
      secure: G566sxEWDq1MxuC/PYRxwCxH9VRoaJ/2pa7623N6LvCNOKTXNxyLHpgwAZUGp3JFApP45BvBi0xRhtnKJj5IwbmZv1VEjQ5SFeqIngPr0kCAyrNItGwznSgwGpgNvUusuEa7MBkf83VSgo2gjZHF/M3xAU81Zu4dI/AtDEDU/D0ee9SCnow6RE0re1r8HjnrOUf7+osMi12jX8GTVZw10gsCPAMAmZHGULTjFCLijDpVsDVoTRKZp634qDKNeK3bak7cWDniXUkIB6Um9EMnRsrImOH7o9zHDD6TFvXKUqEWY4v5mYkI5L4P7q3JWiF4ElqaIsFi3/45vTrFNrYQW73R+M2hjmvwCHbsFyxFk+Evzs0yVh4YFHVG7qua9+4GO1w4WRPDFwWdg83LPUnihoZfBbJnXSpWczZei8yjx/2GB9a2SZ1Eb9ASMt91AnRTc/rhxYZ2IAJD8dtO0mCOTaaDvQ3RVQnkIHVnp6knHBdKmMPy6vaPZU4ZHOTNix8Tq/IhPDVQxIymEPX4UK15LtK68hjW0195XafH+QO4d0e78KZzdYjRvck1cA5fSQEZukBaGR1MkWO3kaVJuI7CgkoP2ZfwPvNpvzNplM2PiQmnB/8tOLUMz9fcjufKrkaVCqlpWLgonxvizlRTn1ODAhKVOfDbF2b1EPKgkkKlfi4=
    bucket: theme.instedd.org
    local_dir: _site
    skip_cleanup: true
    on:
      branch: master
  secret_access_key:
    secure: jPyfsPtakQSFMxCJa/W2lov5+7/zDDl+b36l+3wq13wlN1crCXHRAP0OH5IpiEiPvMFAVld6bKyYHAWUu8xrQtZvhK2KZcigfVp3u3JyuMuOqzxNd2jf93CoFNdjpmyhgHWTanooVfz1nr6sMyOBZqVd8iSGuYCnFMh7XWYogctS8r2LeefNegbwqkKSY45DHhLMzYwf5rpq3Bqs8FN9Tpmosra0Mr9sYQuM/kXR6+gC3R674Ue+4lq1uMt9XpjS/NiwYYOU9t1aGzupzkDXVnhXt+1Izn8aLmZ5O0BI3WWFvcw6UUfQCRl6bf8umpp01I1EtIcJGSfIRJixt52kkne7lI0Rb89c/v+et72vimEHsZVf/aShTTebGJBkq15IVj9bvmN4jQ6u4A21YBj1CZS06J8MTjXKdKeKsQu8Dke7f1YCCqWK1ULc4dRTadnLwNpkfS3peKJZqo6+t/LHV4dxKrrEJKTOCdlRf4DiqFH3Dnl4tv2bptQ5tF+tJ4Kl+dUo2CxKgcOoNQCJ3f1fWs2gb9zKzRNf9YOl+dcqhFfZMmimIdlNf6Eiam4IHxwJmQLpnffk/2uE9PJve/wdiTSqOdTZ+NHPgDL3KqyFosRCqnG+9w/aCJ2dNJZKDEmXA4pvArDJdj6/cjuGzZTgfwmSDEMqjJkVDmsWDs2HeFQ=
